networks:
  exam-buddy-net:
    driver: bridge

services:
  js-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: js-client:latest
    container_name: js-client
    restart: unless-stopped
    init: true
    ports:
      - "5173:5173"
    networks:
      - exam-buddy-net
    # env_file: ./client/.env  # Uncomment if .env file exists
    depends_on:
      - js-server
    # The client uses Vite's preview server for production preview

  js-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: js-server:latest
    container_name: js-server
    restart: unless-stopped
    init: true
    ports:
      - "5000:5000"
    networks:
      - exam-buddy-net
    env_file: ./server/.env
    depends_on:
      - mongo
    # The server requires a .env file in ./server/ (see server/.env.example)

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - exam-buddy-net
    # Uncomment the following to persist MongoDB data on the host
    # volumes:
    #   - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    # No authentication is set by default; configure as needed for production

# Uncomment to enable MongoDB data persistence
# volumes:
#   mongo-data:
